/*
	Header file for structure used to facilitate writing contact onto an
	array every frame.
*/

#ifndef CONTACT_DATA_H
#define CONTACT_DATA_H

#include "contact.h"

namespace pe {

	struct ContactData {

		// Contact array (pointer to its first element)
		Contact* contacts;

		// Default firction generated by a contact
		real friction;

		// default restitution (bounciness) of a contact
		real restitution;

		/*
			The number of contacts that can be generated(used to enhance
			performace).
		*/
		unsigned contactsLeft;

		/*
			How close two objects have to be in order for them to be
			considered colliding.
		*/
		real tolerance;
	};
}

#endif